accounts/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit, name='edit'),
]

dj_job/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views
from .api import *



urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('post-a-job/', views.post_a_job, name='post_a_job'),
    path('contact-us', views.contact, name='contact'),
    path('<slug:category_slug>', views.job_list, name='job_list_category'),
    path('<slug:job_slug>/', views.job_detail, name='job_detail'),

    ### API
    path('api/jobs/', JobListView.as_view(), name='api-list-view'),
    path('api/jobs/<int:id>/', JobDetailView.as_view(), name='api-detail-view'),
]

accounts/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django_countries.fields import CountryField
from django.contrib.auth.models import User, Group
# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)
    age = models.CharField(max_length=2)
    country = CountryField(multiple=False)

    def __str__(self):
        return self.user.username

jobs/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.


JOB_TYPE = (
    ('P', 'Part Time'),
    ('F', 'Full Time'),
)



class Job(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    vacancy = models.IntegerField(default=1)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    job_type = models.CharField(max_length=50, choices=JOB_TYPE)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    published = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)



class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self,*args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)



class Apply(models.Model):
    name = models.CharField(max_length=100)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254)
    cv = models.FileField(upload_to='CV')
    cover_letter = models.TextField()
    website = models.URLField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.name


class Contact(models.Model):
    city = models.CharField(max_length=100)
    phone = PhoneNumberField()
    email = models.EmailField(max_length=254)

    def __str__(self):
        return self.email

jobs/forms.py
from django import forms
from .models import *



class ApplyForm(forms.ModelForm):
    class Meta:
        model = Apply
        fields = '__all__'
        exclude = ['job']



class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude = ['slug', 'owner']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .froms import *
from .models import Profile
from jobs.decorators import *
# Create your views here.



@user_authenticate
def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        email = request.POST.get('email')
        if User.objects.filter(email=email).exists():
            messages.info(request, 'Email Is Already Exist')
            return redirect('register')
        else:
            if form.is_valid():
                form.save()
                return redirect('login')
    return render(request, 'registration/register.html', {'form':form})



@login_required(login_url='login')
def profile(request):
    profile = Profile.objects.get(user=request.user)
    context = {
        'profile':profile
    }
    return render(request, 'profile.html', context)



@login_required(login_url='login')
def edit(request):
    profile = Profile.objects.get(user=request.user)
    p_form = ProfileForm(instance=profile)
    u_form = UserForm(instance=request.user)
    if request.method == 'POST':
        p_form = ProfileForm(request.POST, instance=profile)
        u_form = UserForm(request.POST, instance=request.user)
        if p_form and u_form.is_valid():
            p_form.save()
            u_form.save()
            return redirect('profile')
    context = {
        'p_form' : p_form,
        'u_form' : u_form
    }
    return render(request, 'edit.html', context)

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Count
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from .filters import *
from .decorators import *
# Create your views here.



@login_required(login_url='login')
def job_list(request, category_slug=None):
    category = None
    job = Job.objects.all()
    total = job.count()
    my_filter = jobFilter(request.GET, queryset=job)
    job = my_filter.qs
    category_list = Category.objects.annotate(total_job=Count('job'))


    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        job = job.filter(category = category)

    paginator = Paginator(job, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'job_list.html'
    context = {
        'jobs':page_obj,
        'filter':my_filter,
        'total':total,
        'categories':category_list,
    }
    return render(request, template, context)



@login_required(login_url='login')
def job_detail(request, job_slug):
    job = get_object_or_404(Job, slug=job_slug)
    form  = ApplyForm()
    if request.method == 'POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job
            my_form.save()
            messages.info(request, 'Your Apply Was Requested')
            return redirect('/')
    template = 'job_detail.html'
    context = {
        'job':job,
        'form':form,
    }
    return render(request, template, context)



@login_required(login_url='login')
def post_a_job(request):
    form  = JobForm()
    if request.method == 'POST':
        form = JobForm(request.POST)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.owner = request.user
            my_form.save()
            messages.info(request, 'Your Job Is Ready')
            return redirect('/')
    template = 'post_a_job.html'
    context = {
        'form':form,
    }
    return render(request, template, context)


def contact(request):
    contact = Contact.objects.first()
    if request.method == 'POST':
        subject = request.POST['subject']
        email = request.POST['email']
        message = request.POST['message']
        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [email],
        )
    return render(request, 'contact.html', {'contact':contact})

templates/contact.html
{% extends 'main.html' %}

{% load i18n %}
{% load bootstrap4 %}

{% block head_title %}{% trans 'Contact-Us' %}{% endblock head_title %}

{% block content %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Contact</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <!-- ================ contact section start ================= -->
    <section class="contact-section section_padding">
    <div class="container">
        <div class="row">
        <div class="col-12">
            <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
            <form class="form-contact contact_form" method="POST">
                {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder = 'Enter Subject'>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="form-group">
                        <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder = 'Enter email address'>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder = 'Enter Message'></textarea>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <button type="submit" class="button button-contactForm btn_4 boxed-btn">Send Message</button>
            </div>
            </form>
        </div>
        <div class="col-lg-4">
            <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
                <h3>City</h3>
                <p>{{ contact.city }}</p>
            </div>
            </div>
            <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
                <h3>{{ contact.phone }}</h3>
                <p>Mon to Fri 9am to 6pm</p>
            </div>
            </div>
            <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
                <h3>{{ contact.email }}</h3>
                <p>Send us your query anytime!</p>
            </div>
            </div>
        </div>
        </div>
    </div>
    </section>



{% endblock content %}

templates/edit.html
{% extends 'main.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block head_title %}{% trans 'Edit Profile' %}{% endblock %}

{% block content %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Edit Profile</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form method='POST'>
                            {% csrf_token %}
                            {% if messages %}
                                {% for msg in messages %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button class="close" type="button" data-dismiss="alert" aria-label="close" fdprocessedid="q83sii">×</button>
                                        {{msg}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            {% bootstrap_form u_form %}
                            {% bootstrap_form p_form %}
                            <a href="/accounts/password_change/">Change My Password?</a>
                            <input type="submit" value="Edit" class='boxed-btn3 w-100 mt-3'>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/footer.html
<footer class="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                        <div class="footer_logo">
                            <a href="#">
                                <img src="img/logo.png" alt="">
                            </a>
                        </div>
                        <p>
                            finloan@support.com <br>
                            +10 873 672 6782 <br>
                            600/D, Green road, NewYork
                        </p>
                        <div class="socail_links">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-xl-2 col-md-6 col-lg-2">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                        <h3 class="footer_title">
                            Company
                        </h3>
                        <ul>
                            <li><a href="#">About </a></li>
                            <li><a href="#"> Pricing</a></li>
                            <li><a href="#">Carrier Tips</a></li>
                            <li><a href="#">FAQ</a></li>
                        </ul>

                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                        <h3 class="footer_title">
                            Category
                        </h3>
                        <ul>
                            <li><a href="#">Design & Art</a></li>
                            <li><a href="#">Engineering</a></li>
                            <li><a href="#">Sales & Marketing</a></li>
                            <li><a href="#">Finance</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-4 col-md-6 col-lg-4">
                    <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                        <h3 class="footer_title">
                            Subscribe
                        </h3>
                        <form action="#" class="newsletter_form">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit">Subscribe</button>
                        </form>
                        <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                            luckily.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/job_detail.html
{% extends 'main.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block head_title %}{% trans 'Job Detail' %}{% endblock %}
{% block content %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <h4>{{job}}</h4>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> Part-time</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method='POST' enctype='multipart/form-data'>
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" value="Apply" class='boxed-btn3 w-100'>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published|date:'d M , o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}}k</span></li>
                                <li>Job Nature: <span> {{job.get_job_type_display}}</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

templates/job_list.html
{% extends 'main.html' %}
{% load i18n %}
{% block head_title %}{% trans 'Job Board' %}{% endblock %}
{% load bootstrap4 %}
{% block content %}
    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="single_slider  d-flex align-items-center slider_bg_1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-7 col-md-6">
                        <div class="slider_text">
                            <h5 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".2s">{{total}} Jobs listed</h5>
                            <h3 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".3s">Find your Dream Job</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ilstration_img wow fadeInRight d-none d-lg-block text-right" data-wow-duration="1s" data-wow-delay=".2s">
            <img src="img/banner/illustration.png" alt="">
        </div>
    </div>
    <!-- slider_area_end -->
    <!-- catagory_area -->
    <div class="catagory_area">
        <div class="container">
            <div class="row cat_search" style='margin-top: -50px'>
                <div class="col-lg-9 col-md-4">
                    <form method="GET">
                        <div class="single_input">
                            {% bootstrap_form filter.form %}
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <input type="submit" class='boxed-btn3 w-100 ' style='margin-top: 30px' value='Search'>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ catagory_area -->

    <!-- popular_catagory_area_start  -->
    <div class="popular_catagory_area" style='margin-top: -100px'>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title mb-40">
                        <h3>Popolar Categories</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                
                {% for category in categories %}
                <div class="col-lg-4 col-xl-3 col-md-6">
                    <div class="single_catagory">
                        <a href="{% url 'job_list_category' category.slug %}"><h4>{{category}}</h4></a>
                        <p> <span>{{category.total_job}}</span></p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- popular_catagory_area_end  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area" style='margin-top: -70px'>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="section_title">
                        <h3>Job Listing</h3>
                    </div>
                </div>
            </div>
            <div class="job_lists">
                <div class="row">
                    
                    {% for job in jobs %}
                    <div class="col-lg-12 col-md-12">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{{job.slug}}/"><h4>{{job}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.get_job_type_display}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                    <a href="{{job.slug}}/" class="boxed-btn3">Apply Now</a>
                                </div>
                                <div class="date">
                                    <p>Date line: {{job.published|date:'d M o'}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% if jobs.has_other_pages %}
        <div class="row">
            <div class="col-lg-12">
                <div class="pagination_wrap">
                    <ul>
                        {% if jobs.has_previous %}
                        <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                        {% endif %}
                        
                        {% for p in jobs.paginator.page_range %}
                        <li><a href="?page={{p}}"><span>{{p}}</span></a></li>
                        {% endfor %}
                        {% if jobs.has_next %}
                        <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <!-- job_listing_area_end  -->

{% endblock %}

templates/main.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>

    {% include 'navbar.html' %}

    {% block content %}

    {% endblock content %}

    {% include 'footer.html' %}

    {% include 'scripts.html' %}

</body>

</html>

templates/navbar.html
    {% if request.user.is_authenticated %}
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="/">home</a></li>
                                            <li><a href="/contact-us">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="/accounts/logout/">Logout</a>
                                    </div>
                                    {% if request.user.is_staff %}
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="/post-a-job/">Post a Job</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    {% endif %}